import AnimatedSection from '@/components/AnimatedSection';
import ContactForm from '@/components/ContactForm';
import PageHeader from '@/components/PageHeader';
import { CheckCircle } from 'lucide-react';

const products = [
  { name: 'Deye All-in-one', image: 'https://renewableindustries.co/wp-content/uploads/2025/11/Deye-Battery-1024x1024.png', description: 'A highly dependable home energy storage system that delivers top-tier reliability, ease of use, and long-term peace of mind.', features: ['Safe LFP chemistry', 'Scalable to match needs', '10-year warranty'] },
  { name: 'Hinen Home Battery', image: 'https://renewableindustries.co/wp-content/uploads/2025/11/Hinen-Battery.png', description: 'A high‑quality solution that stands out for its reliable performance, intelligent integration and long‑term durability.', features: ['Durable LFP technology', 'Strong performance guarantee', 'Ideal for backup power'] },
  { name: 'Alpha ESS Smile G3', image: 'https://renewableindustries.co/wp-content/uploads/2025/11/SMILE-G3-T1220.png', description: 'A well‑regarded, modular home energy storage system that offers strong reliability and expansion flexibility.', features: ['Scalable design', 'Robust safety & build quality', 'Excellent integration'] },
  { name: 'Sigenenergy SigenStor', image: 'https://renewableindustries.co/wp-content/uploads/2025/11/sig-battery.png', description: 'A reliable, smart home energy storage system built for seamless performance, flexibility and peace of mind.', features: ['Modular and scalable', 'Smart control via app', 'Strong build for harsh conditions'] },
];

const faqs = [
    { q: 'What is a solar battery?', a: 'A solar battery stores the excess electricity generated by your solar panels so you can use it later, such as at night or during power outages.' },
    { q: 'How long do solar batteries last?', a: 'Most modern lithium-ion batteries last 10–15 years. We install high-quality batteries backed by warranties of 10 years or more.' },
    { q: 'Can I use a solar battery during a blackout?', a: 'Yes, many of our batteries provide backup power during outages, keeping essential appliances running.' },
    { q: 'Can I add a battery to my existing solar system?', a: 'Absolutely! We can retrofit a battery to your current solar setup. Our team will assess your system to recommend the right battery.' },
];

const BatteriesPage = () => {
  return (
    <div>
      <PageHeader title="Battery Solutions" subtitle="A battery backup system gives you reliable power and reduces your reliance on the grid. Always be covered." />
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid lg:grid-cols-3 gap-12">
          <div className="lg:col-span-2 space-y-12">
            <AnimatedSection>
              <h2 className="text-3xl font-bold mb-8 text-center">Our Battery Products</h2>
              <div className="space-y-12">
                {products.map((p, i) => (
                  <div key={i} className="grid md:grid-cols-3 gap-8 items-center bg-slate-900/50 border border-slate-800 p-6 rounded-lg">
                    <img src={p.image} alt={p.name} className="rounded-lg shadow-lg w-full md:w-auto" />
                    <div className="md:col-span-2">
                      <h3 className="text-2xl font-bold text-white">{p.name}</h3>
                      <p className="text-gray-400 mt-2 mb-4">{p.description}</p>
                      <ul className="space-y-2 text-sm">
                        {p.features.map((f, fi) => <li key={fi} className="flex items-center text-gray-300"><CheckCircle className="w-4 h-4 mr-2 text-primary-light"/>{f}</li>)}
                      </ul>
                    </div>
                  </div>
                ))}
              </div>
            </AnimatedSection>

            <AnimatedSection>
                <h2 className="text-3xl font-bold mb-8 text-center">Frequently Asked Questions</h2>
                <div className="space-y-4">
                    {faqs.map((faq, i) => (
                        <details key={i} className="bg-slate-900 border border-slate-800 p-4 rounded-lg cursor-pointer group">
                            <summary className="font-semibold text-white list-none flex justify-between items-center">{faq.q} <span className="transition-transform duration-300 group-open:rotate-45">+</span></summary>
                            <p className="text-gray-400 mt-2 pt-2 border-t border-slate-800">{faq.a}</p>
                        </details>
                    ))}
                </div>
            </AnimatedSection>
          </div>
          <div className="lg:col-span-1">
            <div className="sticky top-28">
              <AnimatedSection>
                <ContactForm title="Speak with a Specialist!" />
              </AnimatedSection>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BatteriesPage;
